# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3283d8223765a739c9a65ccb1776528049b17cd285b32bac41981052af5b492fcac2294140e5d738a5df8b7963928828b201ce91b4758a7b3d1e9a1964bca9c3

test:
  secret_key_base: eba60cc2c425e57d4f9df5c28027d5f592a436920db9890d18c5613e22d8f475e24318004d334344b2614d8a99d0b9889bfaf12841fde44eff56d0f989d5f309

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
